### ISSUE TITLE
Firebase setup

### ISSUE THREAD

**Issue by sbis04** [Soumi7/reaction_lab#1]
## TODO

- [x] Integrate to platforms
- [x] Add auth
- [x] Add firestore
- [x] Upload data to firestore
- [x] Retrieve and show data
