### ISSUE TITLE
Create dashboard page UI

### ISSUE THREAD

**Issue by sbis04** [Soumi7/reaction_lab#2]
### Tasks

- [x] Pass `user` to this screen
- [x] Make an Info section
- [x] Two buttons navigating to Practise & Multiplayer screen
- [x] The app bar * 

> *`AppBar` can contain the user profile icon and something else (decide), take help from the other repo's dashboard 😉
