### ISSUE TITLE
Build MultiplayerScreen

### ISSUE THREAD

**Issue by sbis04** [Soumi7/reaction_lab#3]
### Tasks

- [x] Design the layout
- [x] Capture the formulas (using randomization and syncing b/t users)
- [x] Score section
- [x] Timer
- [x] Drag & drop numbers (from options table)
