### ISSUE TITLE
Room creation screen

### ISSUE THREAD

**Issue by sbis04** [Soumi7/reaction_lab#5]
## Tasks

- [x] Option to create a new room
- [x] Display the available rooms 
- [x] Connect to Firebase for joining and creating rooms
